import Header from "@/components/Header";
import CloudinaryImage from "@/components/CloudinaryImage";
import { Link } from "react-router-dom";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-slate-100 to-slate-200 dark:from-slate-900 dark:via-teal-900 dark:to-emerald-900">
      {/* Navigation */}
      <Header />
      
      {/* Privacy Policy Content */}
      <section className="py-12 md:py-20">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto bg-white/80 dark:bg-slate-800/30 backdrop-blur-md rounded-lg shadow-lg border border-white/20 dark:border-teal-500/20 p-8 md:p-12">
            <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-8 border-b pb-4 border-teal-500/30">Privacy Policy</h1>
            <p className="text-muted-foreground mb-6">Last updated: March 18, 2024</p>
            
            <div className="space-y-8">
              <div>
                <p className="text-foreground mb-4">
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p className="text-foreground mb-4">
                  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-foreground mb-4">Interpretation and Definitions</h2>
                
                <h3 className="text-xl font-medium text-foreground mt-6 mb-3">Interpretation</h3>
                <p className="text-foreground mb-4">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                
                <h3 className="text-xl font-medium text-foreground mt-6 mb-3">Definitions</h3>
                <p className="text-foreground mb-4">For the purposes of this Privacy Policy:</p>
                <ul className="list-disc list-inside space-y-2 text-foreground ml-4 mb-6">
                  <li><span className="font-medium">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><span className="font-medium">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><span className="font-medium">Application</span> refers to Chemouflage, the software program provided by the Company.</li>
                  <li><span className="font-medium">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Eduflage, Dhaka, Bangladesh.</li>
                  <li><span className="font-medium">Country</span> refers to: Bangladesh</li>
                  <li><span className="font-medium">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><span className="font-medium">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
                  <li><span className="font-medium">Service</span> refers to the Application.</li>
                  <li><span className="font-medium">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.</li>
                  <li><span className="font-medium">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li><span className="font-medium">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-foreground mb-4">Collecting and Using Your Personal Data</h2>
                
                <h3 className="text-xl font-medium text-foreground mt-6 mb-3">Types of Data Collected</h3>
                
                <h4 className="text-lg font-medium text-foreground mt-4 mb-2">Personal Data</h4>
                <p className="text-foreground mb-4">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc list-inside space-y-1 text-foreground ml-4 mb-6">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Usage Data</li>
                </ul>
                
                <h4 className="text-lg font-medium text-foreground mt-4 mb-2">Usage Data</h4>
                <p className="text-foreground mb-4">
                  Usage Data is collected automatically when using the Service.
                </p>
                <p className="text-foreground mb-4">
                  Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p className="text-foreground mb-4">
                  When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-medium text-foreground mt-6 mb-3">Information Collected while Using the Application</h3>
                <p className="text-foreground mb-4">
                  While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
                </p>
                <ul className="list-disc list-inside text-foreground ml-4 mb-4">
                  <li>Pictures and other information from your Device's camera and photo library</li>
                </ul>
                <p className="text-foreground mb-4">
                  We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
                </p>
                <p className="text-foreground mb-4">
                  You can enable or disable access to this information at any time, through Your Device settings.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-foreground mb-4">Use of Your Personal Data</h2>
                <p className="text-foreground mb-4">The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc list-inside space-y-2 text-foreground ml-4 mb-6">
                  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                  <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                  <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                  <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                  <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
                  <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                  <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                  <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-semibold text-foreground mb-4">Contact Us</h2>
                <p className="text-foreground">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <p className="text-foreground font-medium mt-2">
                  By email: <a href="mailto:chemouflage.edu@gmail.com" className="text-teal-500 hover:text-teal-400">chemouflage.edu@gmail.com</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-background/80 backdrop-blur-lg border-t border-teal-500/30 py-12">
        <div className="container mx-auto px-4">
          <div className="border-t border-teal-500/30 mt-8 pt-8 text-center text-muted-foreground">
            <div className="flex items-center justify-center">
              <CloudinaryImage
                fileName="Footer-Logo_vd1b65.png"
                alt="AamarPay - Secure Payment Gateway"
                className="h-6 opacity-80 hover:opacity-100 transition-opacity"
                height={24}
                width={400}
              />
            </div>
            <p>&copy; 2025 Chemouflage. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default PrivacyPolicy;