// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkzokjifmxrztttrrnzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrem9ramlmbXhyenR0dHJybnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzQ0NjksImV4cCI6MjA2MzkxMDQ2OX0.gpd0WwrYzKNc-jLhlQ1oDKYS9s0wvN6pCfiyehc4FrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);